import { ambilJson } from "./cache-data.js";
const $=id=>document.getElementById(id), NS="http://www.w3.org/2000/svg", fmt=(v,d=2)=>new Intl.NumberFormat("id-ID",{minimumFractionDigits:d,maximumFractionDigits:d}).format(v);
const svg=(n,a={},t="")=>{const e=document.createElementNS(NS,n);Object.entries(a).forEach(([k,v])=>e.setAttribute(k,String(v)));if(t)e.textContent=t;return e;};
const variableSelect=$("a-peubah"),yearSelect=$("a-tahun"), scatterYear=$("scatter-tahun");
Promise.all([ambilJson("data/moran.json"),ambilJson("data/scatter-moran.json"),ambilJson("data/nilai-wilayah-tahunan.json"),ambilJson("data/indikator.json"),ambilJson("data/peringkat.json")]).then(([moran,weights,values,indicators,ranks])=>{
 const weightLabels={queen:"Queen",jarak_110_km:"Jarak 110 km",knn_5:"KNN 5 tetangga"};
 function drawSensitivity(){const year=yearSelect.value,items=Object.entries(weightLabels).map(([key,label])=>({key,label,...weights.skema[key]?.[year]})).filter(x=>Number.isFinite(x.moran_i)),s=$("sens-chart");s.replaceChildren();$("sens-year").textContent=year;if(!items.length){$("sens-note").textContent="Hasil sensitivitas tidak tersedia untuk tahun ini.";return;}const w=720,h=250,p={l:118,r:24,t:24,b:38},lo=Math.min(0,...items.map(x=>x.moran_i)),hi=Math.max(0,...items.map(x=>x.moran_i)),pad=(hi-lo||1)*.16,x=v=>p.l+(v-lo+pad)/(hi-lo+2*pad)*(w-p.l-p.r),step=(h-p.t-p.b)/items.length;s.append(svg("line",{class:"chart-zero",x1:x(0),x2:x(0),y1:p.t-8,y2:h-p.b}));items.forEach((d,i)=>{const yy=p.t+(i+.5)*step,c=svg("circle",{class:d.q_bh<=.05?"sensitivity-dot significant":"sensitivity-dot",cx:x(d.moran_i),cy:yy,r:7,tabindex:0,role:"img"});c.append(svg("title",{},`${d.label}: I=${fmt(d.moran_i,4)}, p=${fmt(d.p_value,3)}, q BH=${fmt(d.q_bh,3)}, ${d.jumlah_tanpa_tetangga} tanpa tetangga`));s.append(svg("text",{class:"chart-tick","text-anchor":"end",x:p.l-10,y:yy+4},d.label),svg("line",{class:"chart-grid",x1:p.l,y1:yy,x2:w-p.r,y2:yy}),c,svg("text",{class:"chart-tick",x:Math.min(w-p.r-80,x(d.moran_i)+11),y:yy+4},fmt(d.moran_i,3)));});$("sens-note").textContent=`Uji permutasi satu arah, ${weights.metadata.jumlah_permutasi} permutasi. p mentah dan q BH lintas 33 kombinasi disajikan pada tooltip titik. Definisi: ${weights.metadata.catatan}`;}
 function drawChange(){const year=Number(yearSelect.value),variable=variableSelect.value,meta=indicators.find(x=>x.kunci===variable),scale=meta?.satuan==="persen"?100:1,unit=meta?.satuan==="persen"?"poin persentase":meta?.satuan||"nilai",base=values[variable]?.["2015"]||{},now=values[variable]?.[String(year)]||{},s=$("change-chart"),names=Object.keys(base).filter(n=>Number.isFinite(Number(base[n]))&&Number.isFinite(Number(now[n])));$("change-year").textContent=String(year);s.replaceChildren();if(!names.length){$("change-detail").textContent="Tidak cukup data untuk membandingkan tahun ini.";return;}const pairs=names.map(name=>({name,x:Number(base[name]),y:(Number(now[name])-Number(base[name]))*scale})),xmin=Math.min(...pairs.map(d=>d.x)),xmax=Math.max(...pairs.map(d=>d.x)),ymin=Math.min(...pairs.map(d=>d.y)),ymax=Math.max(...pairs.map(d=>d.y)),p={l:58,r:20,t:20,b:42},w=720,h=300,px=v=>p.l+(v-xmin+(xmax-xmin||1)*.06)/(xmax-xmin+(xmax-xmin||1)*.12)*(w-p.l-p.r),py=v=>p.t+(ymax+(ymax-ymin||1)*.1-v)/(ymax-ymin+(ymax-ymin||1)*.2)*(h-p.t-p.b);s.append(svg("line",{class:"chart-zero",x1:p.l,x2:w-p.r,y1:py(0),y2:py(0)}));for(let i=0;i<4;i++){const yy=p.t+i*(h-p.t-p.b)/3,val=ymax-(ymax-ymin)*i/3;s.append(svg("line",{class:"chart-grid",x1:p.l,x2:w-p.r,y1:yy,y2:yy}),svg("text",{class:"chart-tick","text-anchor":"end",x:p.l-7,y:yy+4},fmt(val,1)));}const medianY=[...pairs].sort((a,b)=>a.y-b.y)[Math.floor(pairs.length/2)].y;s.append(svg("line",{class:"chart-median",x1:p.l,x2:w-p.r,y1:py(medianY),y2:py(medianY)}));pairs.forEach(d=>{const c=svg("circle",{class:"change-point",cx:px(d.x),cy:py(d.y),r:3.2,tabindex:0,role:"button"});c.append(svg("title",{},`${d.name}: nilai awal ${fmt(d.x,2)}, perubahan ${fmt(d.y,2)} ${unit}`));const show=()=>{$("change-detail").replaceChildren(document.createTextNode(`${d.name}: nilai awal ${fmt(d.x,2)} · perubahan ${fmt(d.y,2)} ${unit} · `));const a=document.createElement("a");a.href=`peta.html?tahun=${year}&peubah=${encodeURIComponent(variable)}&provinsi=${encodeURIComponent(d.name)}`;a.textContent="Lihat di peta →";$("change-detail").append(a);};c.addEventListener("pointerenter",show);c.addEventListener("focus",show);c.addEventListener("click",show);s.append(c);});s.append(svg("text",{class:"chart-axis-title","text-anchor":"middle",x:(w+p.l-p.r)/2,y:h-5},`Nilai tahun 2015 (${unit})`),svg("text",{class:"chart-axis-title","text-anchor":"middle",transform:`translate(14 ${h/2}) rotate(-90)`},`Perubahan 2015–${year} (${unit})`));}
 function drawLISATransition(){const year=String(yearSelect.value),variable=variableSelect.value,first=moran.moran_dan_lisa[variable]?.["2015"]?.lisa_per_wilayah,last=moran.moran_dan_lisa[variable]?.[year]?.lisa_per_wilayah,root=$("lisa-transition-grid"),cats=["HH","LL","HL","LH","Lain / tidak signifikan"],classify=x=>x?.signifikan&&["HH","LL","HL","LH"].includes(x.kuadran)?x.kuadran:"Lain / tidak signifikan";root.replaceChildren();if(!first||!last){$("lisa-transition-n").textContent="LISA tidak tersedia untuk peubah ini";root.textContent="Pilih Kemiskinan, IPM, Gini, atau TPT untuk melihat perubahan label LISA.";return;}const matrix=Object.fromEntries(cats.map(c=>[c,Object.fromEntries(cats.map(d=>[d,0]))]));let n=0;for(const region of Object.keys(first)){if(!last[region])continue;matrix[classify(first[region])][classify(last[region])]++;n++;}const table=document.createElement("table");table.className="matrix-table";const head=document.createElement("tr");head.append(document.createElement("th"));cats.forEach(c=>{const th=document.createElement("th");th.textContent=c;head.append(th);});const thead=document.createElement("thead");thead.append(head);table.append(thead);const tbody=document.createElement("tbody");cats.forEach(row=>{const tr=document.createElement("tr"),th=document.createElement("th");th.textContent=row;tr.append(th);cats.forEach(col=>{const td=document.createElement("td"),v=matrix[row][col];td.textContent=String(v);td.style.setProperty("--matrix-strength",String(v/Math.max(1,...cats.flatMap(a=>cats.map(b=>matrix[a][b])))));td.title=`${row} tahun 2015 ke ${col} tahun ${year}: ${v} wilayah`;tr.append(td);});tbody.append(tr);});table.append(tbody);root.append(table);$("lisa-transition-n").textContent=`${n} wilayah dengan hasil tersedia pada dua tahun`;}
 function update(){drawSensitivity();drawChange();drawLISATransition();}
 yearSelect.addEventListener("change",update);variableSelect.addEventListener("change",update);document.addEventListener("analisis:update",update);setTimeout(update,0);
}).catch(()=>{$("sens-note").textContent="Data sensitivitas tidak dapat dimuat.";});

